### ISSUE TITLE
请问【waiig】具体书名是什么？

### ISSUE THREAD

**Issue by ghost** [AnkleLiu/interpreter#1]
克隆了你的代码，自己跑了一下
感觉不错
希望深入学习
期待你的回复

**Comment by AnkleLiu** [comment]
write an interpreter in go，把 go 翻译成 js 挺别扭的，凑合看吧😁

**Comment by ghost** [comment]
> write an interpreter in go，把 go 翻译成 js 挺别扭的，凑合看吧😁

好的，谢谢你😊

**Comment by AnkleLiu** [comment]
> > write an interpreter in go，把 go 翻译成 js 挺别扭的，凑合看吧😁
> 
> 好的，谢谢你😊

不客气唉，没想到还能被人看到
